telegram:
  chat_id: "@meteo7737"  # Публичный канал

sites:
  - name: "MeteoInfo"
    url: "https://meteoinfo.ru/pogoda/russia/republic-saha-yakutia/ytyk-kel"
    type: "weather"
    cookies: {}
    schedules:
      weekdays: ["01:00", "02:00", "03:00", "04:00", "10:35", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00"]
      sunday: ["09:00", "21:00"]